# generated by wizard2lm

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Define parameters of trefoil knot
a = 5.0  # Scale factor for the x-coordinate
b = 1.0  # Scale factor for the z-coordinate
c = 0.5  # Scale factor for the y-coordinate
n_turns = 3  # Number of turns in the knot (3 for a trefoil)

# Create a 1D grid for the parameter t
t = np.linspace(0, 4 * np.pi, 1000)

# Define trefoil knot shape
x = a * np.sin(n_turns * t)
y = c * (np.cos(t) + 2 * np.cos(2 * t))
z = b * (np.sin(t) - 2 * np.sin(2 * t))

# Create 3D plot
fig = plt.figure()
ax = fig.add_subplot(111, projection="3d")
ax.plot(x, y, z, color="blue", alpha=0.8)

# Set axis labels and title
ax.set_xlabel("X")
ax.set_ylabel("Y")
ax.set_zlabel("Z")
ax.set_title("Trefoil Knot (3_1)")

plt.ion()  # Enable interactive mode
plt.show(block=True)
